### PR TITLE
Support Org table output

### PR DESCRIPTION
**Pull request by acowley**
Opportunistically interpret output as a table.

### CODE REVIEW

**Comment by gregsexton** [comment]
Wow. Thanks for the PR. This has been on my wish list for a while and I've been putting it off as I thought it would be a pain. I'm curious though, what version of Emacs are you running? I too see the `org-babel-python-table-or-string` function, but I run a (fairly) bleeding edge Emacs. I'm just wondering how I managed to miss this or whether it was added very recently.

**Comment by acowley** [comment]
It's in `ob-python` for me, which is already required. It does seem too easy to be true.

**Comment by gregsexton** [comment]
Which version of Emacs are you running? `M-x version`.

**Comment by acowley** [comment]
```
GNU Emacs 24.5.2 (x86_64-apple-darwin15.3.0, Carbon Version 157 AppKit 1404.34) of 2016-03-04
```

But the function in question is [here](http://orgmode.org/w/?p=org-mode.git;a=blob_plain;f=lisp/ob-python.el).

**Comment by gregsexton** [comment]
Awesome, just wanted to check that it's in a release version of Emacs and you weren't running a 25.x. Will test this out some then merge. :)

**Comment by acowley** [comment]
Hi @gregsexton, any movement here?

**Comment by acowley** [comment]
Any updates?

**Comment by gregsexton** [comment]
Sorry for the delay.

**Pull request closed without merging**
