### PR TITLE
Add support for company-backend doc-buffer

### PR DESCRIPTION
**Pull request by cpbotha**
Whilst going through company-ob-ipython completions, you can request
documentation using f1 or C-h. ob-ipython will inspect the completion
candidate and show the docs using the ob-ipython-inspect
functionality.

I had to factor out the ob-ipython--inspect-code defun in order to be able
to call it from the doc-buffer handling. I also added comments and docs here
and there. Existing functionality remains unchanged.

### CODE REVIEW

**Comment by cpbotha** [comment]
image

**Comment by gregsexton** [comment]
This is very cool. Thanks for sending. I'll be bored on a plane today so will look to merge then. :)

**Comment by cpbotha** [comment]
@gregsexton Please let me know if you need any more inputs to be able to merge this.

It's possible that we want to make more PRs in the future.

**Comment by gregsexton** [comment]
Sorry about this. I merged last week but forgot to push. :D

**Comment by cpbotha** [comment]
Great stuff, thank you for merging!

**Pull request merged**
