### PR TITLE
Return file: prefixed paths for rendered images

### PR DESCRIPTION
**Pull request by jamieforth**
Allows org preview to show them inline.

Without the file: prefix returned links can be opened with org-open-at-point, but they are not displayed inline with org-toggle-inline-images.

### CODE REVIEW

**Comment by jamieforth** [comment]
It used to work for me too, but now without the file: prefix M-x org-redisplay-inline-images no longer has any effect (other file: prefixed links in the buffer display correctly).


GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.20) of 2017-09-12, modified by Debian
Org mode version 9.1.1 (org-plus-contrib-20170918)

**Comment by aijony** [comment]
I have this issue as well. Another option would be removing all the formatting and setting the header
` :output file drawer`

**Comment by cnglen** [comment]
I have the same problem. 
- My emacs.d is forked from https://github.com/purcell/emacs.d. Without file: prefix, C-x C-v not work.
- "emacs -q", without file: prefix, C-x C-v works. 

So there is something wrong with some package in  https://github.com/purcell/emacs.d, I'm not sure the root cause.   At the moment, I use  @jamieforth  's method.

**Comment by gregsexton** [comment]
Just tried this out, and putting the file prefix doesn't seem to do any harm. Happy to merge! Hope this fixes the issue for everyone.

**Pull request merged**
